// <auto-generated />
using API.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Infrastructure.Migrations
{
    [DbContext(typeof(VehicleCatalogDbContext))]
    [Migration("20260911003547_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API.Domain.Entities.CarBrand", b =>
                {
                    b.Property<int>("IdCarBrand")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarBrand"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdCarBrand");

                    b.ToTable("CarBrands", (string)null);

                    b.HasData(
                        new
                        {
                            IdCarBrand = 1,
                            Brand = "Toyota"
                        },
                        new
                        {
                            IdCarBrand = 2,
                            Brand = "Ford"
                        },
                        new
                        {
                            IdCarBrand = 3,
                            Brand = "Chevrolet"
                        },
                        new
                        {
                            IdCarBrand = 4,
                            Brand = "Honda"
                        },
                        new
                        {
                            IdCarBrand = 5,
                            Brand = "Nissan"
                        },
                        new
                        {
                            IdCarBrand = 6,
                            Brand = "Volkswagen"
                        },
                        new
                        {
                            IdCarBrand = 7,
                            Brand = "BMW"
                        },
                        new
                        {
                            IdCarBrand = 8,
                            Brand = "Mercedes-Benz"
                        },
                        new
                        {
                            IdCarBrand = 9,
                            Brand = "Hyundai"
                        },
                        new
                        {
                            IdCarBrand = 10,
                            Brand = "Kia"
                        });
                });

            modelBuilder.Entity("API.Domain.Entities.CarModel", b =>
                {
                    b.Property<int>("IdCarModel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCarModel"));

                    b.Property<int>("IdCarBrand")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("IdCarModel");

                    b.HasIndex("IdCarBrand");

                    b.ToTable("CarModels", (string)null);

                    b.HasData(
                        new
                        {
                            IdCarModel = 1,
                            IdCarBrand = 1,
                            Model = "Corolla",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 2,
                            IdCarBrand = 1,
                            Model = "Hilux",
                            Year = 2023
                        },
                        new
                        {
                            IdCarModel = 3,
                            IdCarBrand = 1,
                            Model = "RAV4",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 4,
                            IdCarBrand = 1,
                            Model = "Yaris",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 5,
                            IdCarBrand = 1,
                            Model = "Land Cruiser",
                            Year = 2026
                        },
                        new
                        {
                            IdCarModel = 6,
                            IdCarBrand = 2,
                            Model = "Mustang",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 7,
                            IdCarBrand = 2,
                            Model = "Ranger",
                            Year = 2023
                        },
                        new
                        {
                            IdCarModel = 8,
                            IdCarBrand = 2,
                            Model = "Explorer",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 9,
                            IdCarBrand = 2,
                            Model = "F-150",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 10,
                            IdCarBrand = 2,
                            Model = "Focus",
                            Year = 2022
                        },
                        new
                        {
                            IdCarModel = 11,
                            IdCarBrand = 3,
                            Model = "Onix",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 12,
                            IdCarBrand = 3,
                            Model = "Tracker",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 13,
                            IdCarBrand = 3,
                            Model = "Silverado",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 14,
                            IdCarBrand = 3,
                            Model = "Cruze",
                            Year = 2023
                        },
                        new
                        {
                            IdCarModel = 15,
                            IdCarBrand = 3,
                            Model = "Camaro",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 16,
                            IdCarBrand = 4,
                            Model = "Civic",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 17,
                            IdCarBrand = 4,
                            Model = "CR-V",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 18,
                            IdCarBrand = 4,
                            Model = "Accord",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 19,
                            IdCarBrand = 4,
                            Model = "HR-V",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 20,
                            IdCarBrand = 4,
                            Model = "Fit",
                            Year = 2022
                        },
                        new
                        {
                            IdCarModel = 21,
                            IdCarBrand = 5,
                            Model = "Sentra",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 22,
                            IdCarBrand = 5,
                            Model = "Versa",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 23,
                            IdCarBrand = 5,
                            Model = "Frontier",
                            Year = 2023
                        },
                        new
                        {
                            IdCarModel = 24,
                            IdCarBrand = 5,
                            Model = "Kicks",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 25,
                            IdCarBrand = 5,
                            Model = "X-Trail",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 26,
                            IdCarBrand = 6,
                            Model = "Golf",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 27,
                            IdCarBrand = 6,
                            Model = "Jetta",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 28,
                            IdCarBrand = 6,
                            Model = "Tiguan",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 29,
                            IdCarBrand = 6,
                            Model = "Polo",
                            Year = 2023
                        },
                        new
                        {
                            IdCarModel = 30,
                            IdCarBrand = 6,
                            Model = "Amarok",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 31,
                            IdCarBrand = 7,
                            Model = "Serie 3",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 32,
                            IdCarBrand = 7,
                            Model = "X5",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 33,
                            IdCarBrand = 7,
                            Model = "Serie 5",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 34,
                            IdCarBrand = 7,
                            Model = "X3",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 35,
                            IdCarBrand = 7,
                            Model = "M4",
                            Year = 2026
                        },
                        new
                        {
                            IdCarModel = 36,
                            IdCarBrand = 8,
                            Model = "Clase C",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 37,
                            IdCarBrand = 8,
                            Model = "GLC",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 38,
                            IdCarBrand = 8,
                            Model = "Clase E",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 39,
                            IdCarBrand = 8,
                            Model = "GLE",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 40,
                            IdCarBrand = 8,
                            Model = "Clase A",
                            Year = 2023
                        },
                        new
                        {
                            IdCarModel = 41,
                            IdCarBrand = 9,
                            Model = "Elantra",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 42,
                            IdCarBrand = 9,
                            Model = "Tucson",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 43,
                            IdCarBrand = 9,
                            Model = "Santa Fe",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 44,
                            IdCarBrand = 9,
                            Model = "Accent",
                            Year = 2023
                        },
                        new
                        {
                            IdCarModel = 45,
                            IdCarBrand = 9,
                            Model = "Creta",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 46,
                            IdCarBrand = 10,
                            Model = "Sportage",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 47,
                            IdCarBrand = 10,
                            Model = "Rio",
                            Year = 2023
                        },
                        new
                        {
                            IdCarModel = 48,
                            IdCarBrand = 10,
                            Model = "Sorento",
                            Year = 2025
                        },
                        new
                        {
                            IdCarModel = 49,
                            IdCarBrand = 10,
                            Model = "Forte",
                            Year = 2024
                        },
                        new
                        {
                            IdCarModel = 50,
                            IdCarBrand = 10,
                            Model = "Picanto",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("API.Domain.Entities.CarModel", b =>
                {
                    b.HasOne("API.Domain.Entities.CarBrand", null)
                        .WithMany()
                        .HasForeignKey("IdCarBrand")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
